- hosts: ubuntu
  tasks:
  - name: check exist
    shell: which docker| grep "not found"
    register: versionInfo
  - shell: |
      sudo snap install docker
      sudo addgroup --system docker
      sudo adduser $USER docker
      newgrp docker
      sudo snap disable docker
      sudo snap enable docker
    when: versionInfo.stdout != ""
  - become: ture
  