- hosts: ubuntu
  tasks:
  - shell: "dpkg -l ubuntu-desktop|grep 'no packages'"
    register: DesktopInfo
    ignore_errors: true
  - name: SET FACT
    set_fact:
      isDesktop: "{{DesktopInfo.stderr == ''}}"
- import_playbook: clash_install.yaml
- import_playbook: chrome_install.yaml
- hosts: ubuntu
  tasks:
    - name: snap proxy
      become: true
      lineinfile:
        dest: /etc/profile
        line: export SYSTEMD_EDITOR="/bin/vim"
    - shell: sudo systemctl restart snapd
      become: true

- hosts: ubuntu
  roles:
    - role: gantsign.git_user
      users:
      - username: "{{ ansible_ssh_user }}"
        git_user_name: huang12zheng
        git_user_email: 805104533@qq.com
        git_user_force: no
- import_playbook: vscode_install.yaml
- import_playbook: ohmyzsh_install.yaml
- import_playbook: k8s_install.yaml