- hosts: ubuntu
  roles:
    - role: gantsign.oh-my-zsh
      users:
      - username: "{{ansible_ssh_user}}"
        oh_my_zsh:
          plugins:
          - bgnotify
          - web-search
          - git
          - microk8s
          - z
          - zsh-syntax-highlighting
          - zsh-autosuggestions
          - alias-finder
          - history
  tasks:
    - name: setup Correct
      lineinfile:
        dest: /home/{{ansible_ssh_user}}/.zshrc
        line: setopt correct
    - name: history set
      lineinfile:
        dest: /home/{{ansible_ssh_user}}/.zshrc
        line: HIST_STAMPS="yyyy-mm-dd"
    - name: install for ohmyzsh
      # become: true
      shell: |
        # git clone git://github.com/wting/autojump.git
        # cd autojump
        # ./install.py
        ZSH_CUSTOM=/home/{{ansible_ssh_user}}/.oh-my-zsh/custom
        [ -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ] || git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions #auto suggestion
        [ -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ] || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting #syntax highlighting
    # - name: .bashrc set
    #   blockinfile:
    #     dest: /home/{{ansible_ssh_user}}/.zshrc
    #     block: |
    #       [ -n "`ps aux | grep clash | grep '\-d'|grep -v grep`" ] && export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
