# https://www.cnblogs.com/wanghao-boke/p/13697596.html
# - hosts: ubuntu
#   become: true
#   tasks:
#     - name: install vscode
#       shell: |
#         # wget https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
#         wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
#         sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
#         sudo apt update
#         sudo apt install code
- hosts: ubuntu
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ansible_ssh_user}}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
            - zbr.vscode-ansible
            - ms-vscode-remote.remote-ssh
            - be5invis.toml
            - zbr.vscode-ansible
            - redhat.vscode-yaml
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true,
            "files.associations": {
              "Vagrantfile": "ruby"
            }
          }
      when: isDesktop