apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-sync
spec:
  selector:
    matchLabels:
      app: apt-sync
  template:
    metadata:
      labels:
        app: apt-sync
    spec:
      containers:
        - name: apt-sync
          image: ustcmirror/apt-sync
          imagePullPolicy: IfNotPresent
          # ports:
          # - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: apt-sync
spec:
  # type: NodePort
  ports:
  - port: 32001
    protocol: TCP
    targetPort: 443
  selector:
    app: apt-sync
  type: ClusterIP