// import 'package:equatable/equatable.dart';

// /// generate by https://javiercbk.github.io/json_to_dart/
// class AutogeneratedSend {
//   final List<SendModel> results;

//   AutogeneratedSend({this.results});

//   factory AutogeneratedSend.fromJson(Map<String, dynamic> json) {
//     List<SendModel> temp;
//     if (json['results'] != null) {
//       temp = List<SendModel>();
//       json['results'].forEach((v) {
//         temp.add(SendModel.fromJson(v as Map<String, dynamic>));
//       });
//     }
//     return AutogeneratedSend(results: temp);
//   }

//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     if (this.results != null) {
//       data['results'] = this.results.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class SendModel extends Equatable {
//   final int id;
//   final String name;

//   SendModel(this.id, this.name);

//   @override
//   List<Object> get props => [id, name];

//   factory SendModel.fromJson(Map<String, dynamic> json) {
//     return SendModel(json['id'] as int, json['name'] as String);
//   }

//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = this.id;
//     data['name'] = this.name;
//     return data;
//   }
  
// }
