import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedSendCencel {
  final List<SendCencelModel> results;

  AutogeneratedSendCencel({this.results});

  factory AutogeneratedSendCencel.fromJson(Map<String, dynamic> json) {
    List<SendCencelModel> temp;
    if (json['results'] != null) {
      temp = List<SendCencelModel>();
      json['results'].forEach((v) {
        temp.add(SendCencelModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedSendCencel(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SendCencelModel extends Equatable {
  final int id;
  final String name;

  SendCencelModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory SendCencelModel.fromJson(Map<String, dynamic> json) {
    return SendCencelModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
  
}
